// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Foot: typeof import('./src/components/foot.vue')['default']
    'Icon:bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Icon:bx:bxsMoon': typeof import('~icons/bx/bxs-moon')['default']
    'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    IconCibHackerrank: typeof import('~icons/cib/hackerrank')['default']
    IconMaterialSymbolsElectricBolt: typeof import('~icons/material-symbols/electric-bolt')['default']
    IconMaterialSymbolsMail: typeof import('~icons/material-symbols/mail')['default']
    IconMdiGithubBox: typeof import('~icons/mdi/github-box')['default']
    IconMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Subscribe: typeof import('./src/components/subscribe.vue')['default']
    Toggletheme: typeof import('./src/components/toggletheme.vue')['default']
  }
}
