// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    'Icon:bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Icon:bx:bxsMoon': typeof import('~icons/bx/bxs-moon')['default']
    'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    'IconMaterialSymbols:clearDay': typeof import('~icons/material-symbols/clear-day')['default']
    'IconMaterialSymbols:clearDayRounded': typeof import('~icons/material-symbols/clear-day-rounded')['default']
    'IconMaterialSymbols:darkMode': typeof import('~icons/material-symbols/dark-mode')['default']
    'IconMaterialSymbols:darkModeOutline': typeof import('~icons/material-symbols/dark-mode-outline')['default']
    'IconMaterialSymbols:sun': typeof import('~icons/material-symbols/sun')['default']
    'IconMaterialSymbols:sunny': typeof import('~icons/material-symbols/sunny')['default']
    'IconMaterialSymbols:sunnyFilled': typeof import('~icons/material-symbols/sunny-filled')['default']
    'IconMaterialSymbols:sunnyOutline': typeof import('~icons/material-symbols/sunny-outline')['default']
    'IconMaterialSymbols:sunnyOutlined': typeof import('~icons/material-symbols/sunny-outlined')['default']
    'IconMaterialSymbols:wbSunny': typeof import('~icons/material-symbols/wb-sunny')['default']
    'IconTabler:moonFilled': typeof import('~icons/tabler/moon-filled')['default']
    IconTablerMoonFilled: typeof import('~icons/tabler/moon-filled')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toggletheme: typeof import('./src/components/toggletheme.vue')['default']
  }
}
